apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: final-tier
  labels:
    role: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: perseverance.azurecr.io/perseverance-project:VERSION
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: final-tier
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    role: frontend
  type: LoadBalancer
